pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "finops-monitor"
        DOCKER_USER = "patilvirupakshi"
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Fetching code from GitHub...'
                git branch: 'main', url: 'https://github.com/Viruthebrave/FinOps-Monitor.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t $DOCKER_USER/$DOCKER_IMAGE:latest ./app'
            }
        }

        stage('Login to DockerHub') {
            steps {
                echo 'Logging into DockerHub...'
                withCredentials([usernamePassword(credentialsId: 'dockerhub-pass', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Push Docker Image to DockerHub') {
            steps {
                echo 'Pushing Docker image to DockerHub...'
                sh 'docker push $DOCKER_USER/$DOCKER_IMAGE:latest'
            }
        }
    }

    post {
        success {
            echo '✅ Build successful! Image pushed to DockerHub.'
        }
        failure {
            echo '❌ Build failed. Check Jenkins logs.'
        }
    }
}
